#include "DBdataGenerator.hpp"

#include <string>

namespace university::data_generator {

const std::vector<std::string> DBdataGenerator::cities {
    "Warszawa",
    "Bydgoszcz",
    "Brzeg",
    "Brodnica",
    "Bartoszyce",
    "Barczewo",
    "Bobolice",
    "Chojnice",
    "Chojna",
    "Cedynia",
    "Dobre Miasto",
    "Dobrzyca",
    "Gdynia",
    "Gliwice",
    "Gniezno",
    "Gubin",
    "Golczewo",
    "Hel",
    "Jaworzno",
    "Jastrowie",
    "Katowice",
    "Kielce",
    "Koszalin",
    "Kalisz",
    "Konin",
    "Krasnystaw",
    "Lublin",
    "Legionowo",
    "Lidzbark",
    "Lesko",
    "Malbork",
    "Mogilno",
    "Miastko",
    "Mrozy",
    "Nysa",
    "Nidzica",
    "Nowy Staw",
    "Olsztyn",
    "Olkusz",
    "Otwock",
    "Opoczno",
    "Olszyna",
    "Piaseczno",
    "Pisz",
    "Puck",
    "Prabuty",
    "Pyzdry",
    "Radom",
    "Rumia",
    "Rawicz",
    "Reda",
    "Resko",
    "Szczecin",
    "Sosnowiec",
    "Sieradz",
    "Sanok",
    "Sopot",
    "Szczytno",
    "Sierpc",
    "Susz",
    "Tychy",
    "Tczew",
    "Tarnobrzeg",
    "Tuchola",
    "Terespol",
    "Ustka",
    "Ustrzyki Dolne",
    "Warszawa",
    "Wejherowo",
    "Warka",
    "Wolin",
    "Warta",
    "Zabrze",
    "Zgierz",
    "Zator"
};

const std::vector<std::string> DBdataGenerator::streets {
    "1 Maja",
    "3 Maja",
    "11 Listopada",
    "Balonowa",
    "Andersa",
    "Armii Krajowej",
    "Balonowa",
    "Bankowa",
    "Bema",
    "Beskidzka",
    "Bielska",
    "Bracka",
    "Browarna",
    "Brzeska",
    "Bytomska",
    "Chmielna",
    "Chopina",
    "Chorzowska",
    "Ciasna",
    "Dworcowa",
    "Dyrekcyjna",
    "Fabryczna",
    "Francuska",
    "Fredry",
    "Gajowa",
    "Garbarska",
    "Gliniana",
    "Gliwicka",
    "Graniczna",
    "Grodzka",
    "Grunwaldzka",
    "Gwarna",
    "Hallera",
    "Hrubieszowska",
    "Jana z Kolna",
    "Janasa",
    "Jezuicka",
    "Kamienna",
    "Kanonia",
    "Karmelicka",
    "Kasprowicza",
    "Katedralna",
    "Katowicka",
    "Kijowska",
    "Klasztorna",
    "Kolejowa",
    "Komuny Paryskiej",
    "Kopernika",
    "Korczaka",
    "Krakowska",
    "Krucza",
    "Krupnicza",
    "Lechicka",
    "Lipowa",
    "Lubelska",
    "Lwowska",
    "Malczewskiego",
    "Mariacka",
    "Mickiewicza",
    "Miodowa",
    "Mostowa",
    "Narutowicza",
    "Nowa",
    "Obozowa",
    "Ogrodowa",
    "Okopowa",
    "Olszewskiego",
    "Opolska",
    "Piekarska",
    "Piwna",
    "Pocztowa",
    "Pomorska",
    "Prosta",
    "Prudnicka",
    "Prusa",
    "Rajska",
    "Reja",
    "Rycerska",
    "Rzeczypospolitej",
    "Senatorska",
    "Sienkiewicza",
    "Sienna",
    "Sikorskiego",
    "Sobieskiego",
    "Stalowa",
    "Starowiejska",
    "Staszica",
    "Stawowa",
    "Struga",
    "Strzelecka",
    "Stwosza",
    "Szeroka",
    "Szewska",
    "Szpitalna",
    "Towarowa",
    "Tuwima",
    "Uniwersytecka",
    "Warszawska",
    "Wawelska",
    "Wiejska",
    "Zachodnia",
    "Zamkowa",
    "Zwierzyniecka",
};
}   // namespace university::data_generator
